#!/usr/bin/env node

'use strict'

var c = require("skilstak-colors");

var n = 1

/*
while (n <= 11){
  process.stdout.write(c.rc() + n +  "Badgers");
  n = n + 1;
}
*/

for (var n = 1; n <= 11; n++) {
  console.log(c.rc() + n + " Badgers");
}

console.log(c.multi("Mushroooooms"));
